import os
import sys

# prevents generated bytecode from cluttering the project
sys.dont_write_bytecode = True
os.environ["QT_API"] = "pyside6"

from PySide6.QtWidgets import QApplication

from ui import SimulatorWindow


if __name__ == "__main__":
    application = QApplication(sys.argv)
    application.setStyle("Fusion")
    window = SimulatorWindow()
    window.show()
    sys.exit(application.exec())
